[package]
name = "annotator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.0"
fltk = "1.3.31"
image = "0.24.5"
rfd = "0.11.1"
walkdir = "2.3.2"

